module.exports = {
  arg: 'param',
  argument: 'param',
  constructor: 'class',
  const: 'constant',
  defaultvalue: 'default',
  desc: 'description',
  emits: 'fires',
  exception: 'throws',
  fileoverview: 'file',
  func: 'function',
  host: 'external',
  linkcode: 'link',
  linkplain: 'link',
  virtual: 'abstract',
  method: 'function',
  overview: 'file',
  prop: 'property',
  return: 'returns',
  var: 'member',
};
